### ISSUE TITLE
Fix Linting Failures

### ISSUE THREAD

**Issue by deHank** [vcuse/SE-Neurology-WebClient#55] opened 2024-11-11 20:28 UTC
** Since we upgraded the Lint version on this project, there have been linting failures when trying to automatically build on deployment ** 

For now I'm gonna set it to ignore linting issues, but we do eventually want to fix them bc it will help our codebase organization.

![Image](https://github.com/user-attachments/assets/52ebbe78-8f7c-41b7-b0a2-4ed5d8781ba4)

**Comment by samuelsarzaba** [comment] 2024-11-18 23:24
Fixed them, however kinda did a bandaid fix for this hydration warning, could be caused by an extension but might want to look into it more later.

**Closed by samuelsarzaba** 2024-11-18 23:24 UTC
Labels: bug, help wanted
